= liquibase-base

The Liquibase project for the module-base
collects the changesets necessary to build
the database schema of the module-base.

Referenced project: link:https://github.com/Evocelot/module-base[module-base]

== Technologies Used

* mariadb:11.3.2
* liquibase:mysql
* docker and docker compose

== Directory Structure

[source,txt]
----
/docs <1>
/docker <2>
/changelog <3>

----
<1> - The source of the project's documentation.
<2> - Scripts used for running the project in a dockerized environment.
<3> - The changelog to be executed by Liquibase.

== Running the Project

=== Starting the DBMS

To run MariaDB in a dockerized environment, execute the following command from the root directory of the project:

.start-local-mariadb
[source,bash]
----
docker compose -f docker/docker.compose.local.mariadb.yml up -d
----

=== Running Liquibase Scripts

To execute the changelog, run the following command from the root directory of the project:

.run-liquibase-changelog
[source,bash]
----
docker compose -f docker/docker.compose.local.modulebase.liquibase.yml up -d
----

=== Starting the DBMS Client (optional)

If needed, you can also start phpMyAdmin by running the following command:

.run-local-phpmyadmin (optional)
[source,bash]
----
docker compose -f docker/docker.compose.local.phpmyadmin.yml up -d
----

====
The default user:

- username: root
- password: admin

====

== Documentation

The documentation is available here: link:docs/index.adoc[Documentation]
